#ifndef __wxUIIClient__
#define __wxUIIClient__

/**
@file
Subclass of IClient, which is generated by wxFormBuilder.
*/

#include "wxUI.h"

#include "Comm.h"

template < typename TChatClient >
class TWorkerWnd : public ui::IWorkerWnd {
public:
	using this_t = TWorkerWnd<TChatClient>;
	using base_t = ui::IWorkerWnd;

	std::optional<TChatClient> m_client;

public:
	TWorkerWnd(wxWindow* parent, std::string const& ip, int port) : ui::IWorkerWnd(parent) {
		Bind(wxEVT_IP_COMM, &this_t::OnEvtIPComm, this, GetId());
		m_client.emplace(this, ip, port);
		m_client->Start();
	}
	~TWorkerWnd() {
		if (m_client) {
			m_client->Stop();
			m_client.reset();
		}
		Unbind(wxEVT_IP_COMM, &this_t::OnEvtIPComm, this, GetId());
		Log("Client Closed");
	}

	virtual void OnTimer_UpdateUI( wxTimerEvent& event ) override {
	}
	virtual void OnTextEnter_Message( wxCommandEvent& event ) override {
		OnButtonClick_Send(event);
	}
	virtual void OnTextEnter_Parameters( wxCommandEvent& event ) override {
		OnButtonClick_Send(event);
	}
	virtual void OnButtonClick_Send( wxCommandEvent& event ) override {
		if (!m_client)
			return;
		auto str = ui_textMessage->GetValue();
		xChatMessage msg = str.ToStdString();
		m_client->Write(msg);
		ui_log->AppendText("Sent: ");
		ui_log->AppendText(msg);
		ui_log->AppendText("\n");
	}
	virtual void OnButtonClick_Close( wxCommandEvent& event ) override {
	}

	void OnEvtIPComm(xEvtIPComm& event) {
		switch (event.m_evt) {
		case xEvtIPComm::EVT_CONNECTED:
			Log("Connected");
			break;
		case xEvtIPComm::EVT_NOT_CONNECTED:
			Log("NOT Connected");
			Close();
			break;
		case xEvtIPComm::EVT_DISCONNECTED:
			Log("Disconnected");
			Close();
			break;
		case xEvtIPComm::EVT_MESSAGE:
			ui_log->AppendText("Recv: ");
			ui_log->AppendText(event.m_msg);
			ui_log->AppendText("\n");
			auto r = ui_log->GetLastPosition();
			ui_log->ShowPosition(r);
			//ui_log->Replace(-1, -1, "\n");
			break;
		}
	}
};

using xWorkerWnd = TWorkerWnd<xChatClient>;
using xUDPWorkerWnd = TWorkerWnd<xChatClientUDP>;

#endif // __wxUIIClient__
