#ifndef __wxUIIClient__
#define __wxUIIClient__

/**
@file
Subclass of IClient, which is generated by wxFormBuilder.
*/

#include "wxUI.h"

#include "Comm.h"

/** Implementing IClient */
class xWorkerWnd : public ui::IWorkerWnd {
public:
	/** Constructor */
	xWorkerWnd(wxWindow* parent, asio::io_context& io, asio::ip::tcp::resolver::results_type const& endpoints);

protected:
	// worker
	xChatClient m_client;

	virtual void OnTimer_UpdateUI( wxTimerEvent& event ) override;
	virtual void OnTextEnter_Message( wxCommandEvent& event ) override;
	virtual void OnTextEnter_Parameters( wxCommandEvent& event ) override;
	virtual void OnButtonClick_Send( wxCommandEvent& event ) override;
};

#endif // __wxUIIClient__
